user  nginx;
worker_processes auto;
pid /run/nginx.pid;

events {
	worker_connections 8192;
	multi_accept on;
    use epoll;
}

http {

    ## SAMPLE nginx.conf file

	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 90s;
	keepalive_requests 1000;
	server_tokens off;
	client_body_buffer_size 32k;
	client_header_buffer_size    16k;
	client_max_body_size 50M;
	types_hash_max_size 2048;
	server_names_hash_bucket_size 64;
	server_names_hash_max_size 4096;
	large_client_header_buffers 4 16k;
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=all:32m max_size=10g;    
    proxy_cache_path /var/cache/ram levels=1:2 keys_zone=ram:30m inactive=3d max_size=1G;
	# Our request limiter zone for wp-login attacks (used in Fail2Ban nginx-limit-req filter and jail)
	limit_req_zone $binary_remote_addr zone=wp-login:10m rate=1r/s;

    # DDos Mitigation
    # ***************
    # https://www.nginx.com/blog/mitigating-ddos-attacks-with-nginx-and-nginx-plus/
    # Limiting the Rate of Requests
    #limit_req_zone $binary_remote_addr zone=flood:50m rate=90r/s;
    # Limiting the Number of Connections
    #limit_conn_zone $binary_remote_addr zone=addr:50m;


	# Add FastCGI caching
	# https://www.nginx.com/blog/9-tips-for-improving-wordpress-performance-with-nginx/

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# SSL Settings
	##
    # Your own SSL settings here if using SSL

	##
	# Logging Settings
	##
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

   access_log  /var/log/nginx/access.log  main;

	##
	# Gzip Settings
	##

	gzip on;
	gzip_disable "MSIE [1-6]\.";
	gzip_vary on;
	gzip_static on;
	gzip_min_length 20;
	gzip_proxied expired no-cache no-store private auth;
	gzip_comp_level 7;
	gzip_buffers 32 4k;
	gzip_http_version 1.1;
	gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

	##
	# Virtual Host Configs
	##

	# Our globalblacklist.conf Bot Blocker Gets Included Because it is placed into the conf.d folder
	# which is loaded by the include below
	include /etc/nginx/conf.d/*.conf;

	#real ip cloudflare
	real_ip_recursive on;
	set_real_ip_from 103.21.244.0/22;
	set_real_ip_from 103.22.200.0/22;
	set_real_ip_from 103.31.4.0/22;
	set_real_ip_from 104.16.0.0/12;
	set_real_ip_from 108.162.192.0/18;
	set_real_ip_from 131.0.72.0/22;
	set_real_ip_from 141.101.64.0/18;
	set_real_ip_from 162.158.0.0/15;
	set_real_ip_from 172.64.0.0/13;
	set_real_ip_from 173.245.48.0/20;
	set_real_ip_from 188.114.96.0/20;
	set_real_ip_from 190.93.240.0/20;
	set_real_ip_from 197.234.240.0/22;
	set_real_ip_from 198.41.128.0/17;
	set_real_ip_from 2400:cb00::/32;
	set_real_ip_from 2606:4700::/32;
	set_real_ip_from 2803:f800::/32;
	set_real_ip_from 2405:b500::/32;
	set_real_ip_from 2405:8100::/32;
	set_real_ip_from 2c0f:f248::/32;
	set_real_ip_from 2a06:98c0::/29;
	set_real_ip_from 10.0.0.0/16;
	set_real_ip_from 172.31.0.0/16;
	real_ip_header CF-Connecting-IP;
}
